# Generated by Django 5.1.5 on 2026-02-28 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRunModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('repository_name', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('commit_sha', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('vulnerabilities_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pipeline_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('cve_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Info')], max_length=10)),
                ('cvss_score', models.FloatField(default=0.0)),
                ('package_name', models.CharField(max_length=255)),
                ('package_version', models.CharField(max_length=50)),
                ('fix_version', models.CharField(blank=True, max_length=50, null=True)),
                ('remediation_status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('ACCEPTED_RISK', 'Accepted Risk'), ('FALSE_POSITIVE', 'False Positive')], default='OPEN', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='persistence.pipelinerunmodel')),
            ],
            options={
                'db_table': 'vulnerabilities',
                'ordering': ['-detected_at'],
            },
        ),
    ]
